# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  check:
    docker:
      - image: yunion/centos-build:go-1.18.3-0
        environment:
          ONECLOUD_CI_BUILD: "1"
    working_directory: /root/go/src/yunion.io/x/onecloud-operator
    steps:
      - checkout
      - run:
          command: |
            make check
  build:
    requires:
      - check
    docker:
      - image: yunion/centos-build:go-1.18.3-0
        environment:
          ONECLOUD_CI_BUILD: "1"

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /root/go/src/yunion.io/x/onecloud-operator
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          key: onecloud-operator-build-cache-{{ checksum "go.mod" }}-{{ checksum "Makefile" }}
          paths:
            - /root/.cache/go-build
      - run:
          command: |
            make
            ls -lh _output/bin/
      - save_cache:
          key: onecloud-operator-build-cache-{{ checksum "go.mod" }}-{{ checksum "Makefile" }}
          paths:
            - /root/.cache/go-build
      - store_artifacts:
          path: _output/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          requires:
            - check
