apiVersion: v1
kind: Namespace
metadata:
  name: onecloud
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onecloud-operator
subjects:
- kind: ServiceAccount
  namespace: onecloud
  name: onecloud-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: onecloud
  name: onecloud-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: onecloud-operator
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  namespace: onecloud
  name: onecloud-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: onecloud-operator
  template:
    metadata:
      labels:
        k8s-app: onecloud-operator
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: onecloud-operator
      containers:
      - name: onecloud-operator
        image: registry.cn-beijing.aliyuncs.com/yunionio/onecloud-operator:v3.7.5
        imagePullPolicy: Always
        command: ["/bin/onecloud-controller-manager", "-sync-user"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
